{
    "品牌":[
        "惊天华盛",
        "华南金牌",
        "金河田",
        "HP",
        "QRTECH",
        "麦本本",
        "Xiaomi/小米",
        "华硕",
        "Intel",
        "Apple/苹果",
        "联想",
        "宁美国度",
        "Dell",
        "技嘉",
        "IPASON/攀升",
        "alienware",
        "UDON/联顿",
        "微软",
        "神州",
        "富士通",
        "ThinkPad",
        "MACHENIKE",
        "华为",
        "ViewPaker/优威派克",
        "东芝",
        "微星",
        "THUNDEROBOT",
        "MAINBOARD/科脑",
        "BUBALUS/大水牛",
        "AMD",
        "三星",
        "honor/荣耀",
        "炫龙",
        "Aoc"
    ],

    "选购热点":[
        "游戏",
        "独显",
        "八核",
        "一体机",
        "高配",
        "四核",
        "网吧",
        "水冷",
        "六核",
        "迷你电脑",
        "双核",
        "二手电脑",
        "设计",
        "至强",
        "大板",
        "钢化玻璃",
        "超薄",
        "16核",
        "无线蓝牙"
    ],

    "内存容量":[
        "512GB",
        "521MB",
        "256GB",
        "128GB",
        "64GB",
        "32GB",
        "16GB",
        "12GB",
        "8GB",
        "8GBx2根",
        "8g",
        "8GB(2个4GB)",
        "8GBx4根",
        "6GB",
        "4GB",
        "4G",
        "4GBx2根",
        "3GB",
        "2GB",
        "1GB"
    ],

    "CPU类型":[
        "Intel/英特尔酷睿",
        "Intel/英特尔至强E5",
        "Intel/英特尔酷睿i7",
        "Core/酷睿i5",
        "INTEL XEON",
        "AMD-FX",
        "Celeron/赛扬",
        "Intel/英特尔酷睿i3",
        "Intel Core/酷睿i3",
        "AMD NPU",
        "Inter Pentium/奔腾",
        "Core/酷睿i7",
        "Intel/英特尔至强E7",
        "Intel/英特尔至强E3",
        "Intel/英特尔奔腾"
    ],

    "筛选条件":[
        "硬盘容量 v",
        "适用场景 v",
        "显卡类型 v",
        "核心数 v",
        "相关分类 v"
    ]

}